---
title: "Painel Covid - AM091"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
    social: menu
    theme: cosmo 
    navbar:  
      - {title: "Covid-R.M.Campinas", icon: glyphicon-signal, href: https://covid-rmc.netlify.app}
      - {title: "Github", icon: fa-github, href: https://github.com/Elizemiku/PainelCovidUnicamp}
---

```{r}
options(knitr.duplicate.label = 'allow', dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

<!-- podemos criar um chunk pegando os codigos do twitter de um R script depois -->

```{r setup, include=FALSE}
library("tidyverse")
library("plotly")
library("flexdashboard")
library("shiny")
library("shinyWidgets")
library(geobr)
library(gganimate)
```

```{r}
#Dados da Covid-19 no Estado de SP
link <- "https://raw.githubusercontent.com/seade-R/dados-covid-sp/master/data/dados_covid_sp.csv"
covid <- read_csv2(link)

#Shapefile do estado de SP com divisão de municípios
mapa <- read_municipality(code_muni = 35, year = 2018)

#Pegando somente as regiões de saúde
regioes <- covid %>% drop_na() %>% select(nome_drs) %>% unique() %>% unlist() %>% unname()
#Adiciono Santos e São Paulo, pois suas regiões estão como baixada santista e grande São Paulo
regioes <- c(regioes, "Santos", "São Paulo")

#Crio um df com o nome do município + coordenadas
covid_regioes <- covid %>% 
  drop_na() %>% 
  select(nome_munic, latitude, longitude) %>% 
  filter(nome_munic %in% regioes) %>% 
  unique()

#Crio um df com o total da covid (casos e óbitos) por data e por região.
evolucao_casos <- covid %>% 
  group_by(datahora, nome_drs) %>% 
  summarise(casos_regiao = sum(casos), pop_regiao = sum(pop), obitos_regiao = sum(obitos)) %>%
  ungroup() %>% 
  #Altero o nome das regiões para as referentes cidades antes da junção dos dados
  mutate(nome_drs = replace(nome_drs, nome_drs == "Grande São Paulo", "São Paulo")) %>% 
  mutate(nome_drs = replace(nome_drs, nome_drs == "Baixada Santista", "Santos")) %>% 
  left_join(covid_regioes, by = c("nome_drs" = "nome_munic")) %>% 
  drop_na()

#Mapa
mapa_ani <- ggplot(evolucao_casos) + 
  geom_sf(data = mapa, fill = "cyan4", color="black", size=.15, ) +
  geom_point(aes(x = longitude, y = latitude, group = nome_drs, 
                 size = 100000*(casos_regiao/pop_regiao),
                 color = 100000*(casos_regiao/pop_regiao)), alpha = .5) +
  scale_size_continuous(range = c(4, 12)) +
  scale_color_gradient(low = "darkgoldenrod1", high = "brown3")+
  guides(color=guide_legend(title = "Casos por 100.000 hab."), 
         size = guide_legend(title = "Casos por 100.000 hab."))+
  theme_void()+
  labs(title = "Evolução da Covid-19 em São Paulo")

#Vou mexer mais na animação amanhã 
```

Covid {data-navmenu="Análise de dados" data-icon="glyphicon-asterisk"}
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
# tirei a opcao de escolher os dados porque podemos usar as abas das paginas para separar , ai depois vcs votam na melhor opcao haha

# seleção das Cidades
selectInput(
  inputId = "nome_munic", 
  label = "Cidades", 
  choices = c(covid$nome_munic),
  selected = "Campinas",
  multiple = TRUE)

 selectInput("Graficos", label = h4("Gráficos"), 
    choices = c("Barras","Linhas","Mapas"), 
    selected = "Linhas",
    multiple = FALSE)

selectInput("ObitosCasos", label = h4("Obitos e casos"), 
    choices = c("Obitos","Casos"), 
    selected = "Obitos",
    multiple = FALSE)
```

Outputs
-----------------------------------------------------------------------

### Grafico de Casos de Covid

```{r}
# filtro reativo das cidades 
filtro_cidades <- reactive({
  covid %>%  filter(nome_munic %in% input$nome_munic)
})

renderPlotly({

  if(input$Graficos == "Linhas"){
    ggplotly(
      ggplot(filtro_cidades(), 
             aes(x = semana_epidem, y = casos, color= nome_munic)) +
      geom_line() +
      labs(title = "Covid-19 por Cidade", 
           subtitle = "Por semanas epideomiológicas") +
      theme_bw())
  }
  
  # so um exemplo pra ver se funciona
  else{
    if(input$Graficos == "Barras"){
    ggplotly(
      ggplot(filtro_cidades(), 
             aes(x = semana_epidem, y = casos, fill= nome_munic)) +
      geom_bar(stat="identity", position = "dodge") +
      theme_bw()) 
    }
    else{
      if(input$Graficos == "Mapas"){
      }
    }
  }
  
})

```

Evolução (Gráfico animado) {data-navmenu="Extra" data-icon="glyphicon-search"}
=====================================  

Nuvem de palavras das autoridades {data-navmenu="Extra" data-icon="fa-hashtag"}
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("twitter", label = h4("Escolha a pessoa do twitter"), 
    choices = c("Bolsonaro","Dilma"), 
    selected = "Bolsonaro",
    multiple = FALSE)
```

Sobre {data-icon="fa-info-circle"}
=====================================  

